#= require jquery
#= require jquery-ui
#  require jquery-migrate
#= require jquery_ujs
#= require bootstrap
#= require template/bootstrap-hover-dropdown
#= require template/html5shiv
#= require template/respond.min
#= require template/jquery.metisMenu
#  require template/jquery.slimscroll
#  require template/jquery.cookie
#  require template/icheck.min
#= require template/custom.min
#= require template/jquery.menu
#  require template/pace.min
#  require template/holder
#  require template/responsive-tabs
#  require template/zabuto_calendar.min
#= require template/main
#= require turbolinks
#= require_tree .
